#!/bin/bash
set -ex
# add bitcoind from the official PPA
# install bitcoind (from PPA) and make
sudo apt-get update 
sudo apt-get install --yes software-properties-common 
sudo add-apt-repository --yes ppa:bitcoin/bitcoin 
sudo apt-get update
sudo apt-get install --yes bitcoind make